index/urls.py
# urlパスを作成
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.table, name='index'),
    path('delete/', views.delete, name='delete'),
    path('register_class/', views.register_class, name='register_class'),
    path('create_class/', views.create_class, name='create_class'),
    path('change_class/', views.change_class, name='change_class'),
    path('save_change_class/', views.save_change_class, name='save_change_class'),
    path('information/', views.information_of_class, name='information'),
    path('upload/', views.upload, name='upload'),
    path('trace/', views.trace, name='trace'),
    path('news/', views.news, name='news'),
]

tclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('auth/', include('auth_app.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/forms.py
from django import forms
from .models import Information, User, MyClass

DAYS = (
    (None, ''),
    ('monday', '月曜日'),
    ('tuesday', '火曜日'),
    ('wednesday', '水曜日'),
    ('thursday', '木曜日'),
    ('friday', '金曜日'),
)

PERIODS = (
    (None, ''),
    ('1', '1時間目'),
    ('2', '2時間目'),
    ('3', '3時間目'),
    ('4', '4時間目'),
    ('5', '5時間目'),
)



class InformationForm(forms.Form):
    title = forms.CharField(
        label = 'タイトル',
        max_length = 50,
        required = True,
        widget = forms.TextInput,
    )
    pictures = forms.ImageField(
        label = '画像',
        required = False,
        widget = forms.ClearableFileInput(attrs={'multiple': True}),
    )
    comment = forms.CharField(
        label = 'コメント',
        required = False,
        widget = forms.Textarea(attrs={'cols': 20, 'rows': 7}),
    )
    def get_pictures(self):
        pictures_list = []
        for i in range(5):
            try:
                picture_object = self.files.getlist('pictures')
                pictures_list.append(picture_object[i])
            except:
                pictures_list.append(None)
        return pictures_list



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'password']

        
class RegisterClassForm(forms.Form):
    name = forms.CharField(
        label = '授業名',
        max_length = 50,
        required = True,
        widget = forms.TextInput(attrs={'class':'form-control'}),
    )
    day = forms.ChoiceField(
        label = '曜日',
        choices = DAYS,
        required = False,
        widget=forms.widgets.Select(attrs={'class':'form-control'}),
    )
    period = forms.ChoiceField(
        label = '時間',
        choices = PERIODS,
        required = False,
        widget=forms.widgets.Select(attrs={'class':'form-control'}),
    )
    place = forms.CharField(
        label = '教室',
        max_length = 50,
        required = False,
        widget = forms.TextInput(attrs={'class':'form-control'}),
    )

templates/index/change_class.html
{% extends 'index.html' %}
{% load static %}
{% block title %}時間割変更{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="main">
    <table border="1" class="class_table">
        <tr class="per5_hei">
            <td></td>
            <td>月</td>
            <td>火</td>
            <td>水</td>
            <td>木</td>
            <td>金</td>
        </tr>
        {% for classlist in classlists %}
        <tr class="class_tr">
            <td>{{ forloop.counter }}</td>
            {% for myclass in classlist %}
            <td class="class_td">
                <p>{{ myclass.name }}</p>
                <form action="{% url 'app:save_change_class' %}" method="POST">
                <select class="select_line" name="{{ forloop.counter }}_{{ forloop.parentloop.counter }}" onchange="submit(this.form)">
                    <option value="null">なし</option>
                    {% for classes in allclasses %}
                    {% if classes.name == myclass.name %}
                    <option value="{{ classes.name }}" selected>{{ classes.name }}</option>
                    {% else %}
                    <option value="{{ classes.name }}">{{ classes.name }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                {% csrf_token %}
                </form>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <div class="config">
        <a href="{% url 'app:index' %}" class="change_class_submit_button">完了</input>
    </div>
</div>
{% endblock %}

templates/index/information.html
{% extends 'index.html' %}
{% load static %}
{% block title %}{{class_name}}情報一覧{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="bg_blue">
    <a href="{% url 'app:index' %}"><button id="back-btn">戻る</button></a>
    <h1 class="name_title">{{class_name}}</h1>
    <hr>
</div>
<a href="{% url 'app:upload' %}"><button class="fs10">うｐ</button></a>
<br>
<input id="search-input" type="text" placeholder="">
<button onclick="search()" class="fs10">検索</button>
<form action="{% url 'app:delete' %}" method="post">
    <input type="submit" value="削除">
    {% for information in informations reversed %}
        <div class="border-1">
        <h2 class="information-title" id="title_{{ forloop.counter }}">{{ information.title }}</h2>
        {% if information.picture1 %}
        <img src='{{ MEDIA_URL }}{{information.picture1}}' width=200>
        {% endif %}
        {% if information.picture2 %}
        <img src='{{ MEDIA_URL }}{{information.picture2}}' width=200>
        {% endif %}
        {% if information.picture3 %}
        <img src='{{ MEDIA_URL }}{{information.picture3}}' width=200>
        {% endif %}
        {% if information.picture4 %}
        <img src='{{ MEDIA_URL }}{{information.picture4}}' width=200>
        {% endif %}
        {% if information.picture5 %}
        <img src='{{ MEDIA_URL }}{{information.picture5}}' width=200>
        {% endif %}
        {% if information.comment  %}
        <p>{{ information.comment }}</p>
        {% endif %}
        <input type="checkbox" name="delete_id" value="{{information.id}}">
        </div>
    {% endfor %}
    {% csrf_token %}
</form>
<script type="text/javascript" src="{% static 'information.js' %}"></script>
{% endblock %}

templates/index/news.html
{% extends 'index.html' %}
{% load static %}
{% block title %}ニュース{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="bg_blue">
<h1 class="name_title">{{class_name}}</h1>
<hr>
</div>
<div class="back">
    <a href="{% url 'app:index' %}" value="戻る" class="back_button_1">戻る</a>
</div>
{% for date, news_list in news_data.items %}
<div class="m-5">
    <h2>日付: {{ date|date:"Y/m/d" }}</h2>
    {% for news in news_list %}
    <div class="m-5">
        <h3>科目： {{ news.class_ }}</h3>
        <h4>タイトル： {{ news.title }}</h4>
        <h4>LETUS url： <a href="{{ news.url }}">{{ news.url }}</a></h4>
    </div>
    {% endfor %}
    <hr>
</div>
{% endfor %}
<form action="{% url 'app:news' %}" method="post">
    {% csrf_token %}
    <div class="mg30 form_title">
        学籍番号 : <input name="student_num" type="text">
    </div>
    <div class="mg30 form_comment">
        パスワード : <input name="letus_password" type="password">
    </div>
    <div class="mg30 form_upload">
        <input type="submit" value="get news" class="upload_button_1">
    </div>
</form>
{% endblock %}

templates/index/register_class.html
{% extends 'index.html' %}
{% load static %}
{% block title %}授業登録{% endblock %}

{% block head_extend %}
<link href="{% static 'index.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="title-logo">
    <h1>最後まで諦めるなよ</h1>
</div>
<div class="container login-form">
    <div class="row">
        <div class="col-md-6 offset-md-3 form-box">
            <form action="{% url 'app:create_class' %}" method="post">
                {% csrf_token %}
                <div class="error">{{ error }}</div>
                <div class="form-group">
                    {{ form.as_p }}
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">登録</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mg30 back">
    <a href="{% url 'app:index' %}" value="戻る" class="back_button_1">戻る</a>
</div>
{% endblock %}

templates/index/table.html
{% extends 'index.html' %}
{% load static %}
{% block title %}時間割{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="main">
    <table border="1" class="class_table">
        <tr class="per5_hei day">
            <td></td>
            <td>月</td>
            <td>火</td>
            <td>水</td>
            <td>木</td>
            <td>金</td>
        </tr>
        {% for classlist in classlists %}
        <tr class="class_tr">
            <td>{{ forloop.counter }}</td>
            {% for myclass in classlist %}
            <td class="class_td">
                {% if myclass.name %}
                <input type="hidden" form="class-form_{{myclass.name}}" name="class_name" value="{{myclass.name}}"></input>
                <input type="submit" form="class-form_{{myclass.name}}" name="{{myclass.name}}" id="{{myclass.name}}_id" class="class_button_1">
                <label for="{{myclass.name}}_id">
                    <div class="one_class">
                        <p>{{myclass.name}}</p>
                        <p>{{ myclass.place }}</p>
                    </div>
                </label>
                <form id="class-form_{{myclass.name}}" action="{% url 'app:information' %}"　name="{{myclass.name}}" method="POST">{% csrf_token %}</form>
                {% endif %}
            </td>
            </td>
            </label>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <div class="config">
        <div class="config_item">
            <a href="{% url 'app:register_class' %}" class="configbutton">授業作成</a>
        </div>
        <div class="config_item">
            <a href="{% url 'app:change_class' %}" class="configbutton">授業変更</a>
        </div>
        <div class="config_item">
            <a href="{% url 'app:trace' %}" class="configbutton">トレース</a>
        </div>
        <div class="config_item">
            <a href="{% url 'app:news' %}" class="configbutton">お知らせ</a>
        </div>
    </div>
</div>
{% endblock %}

templates/index/trace.html
{% extends 'index.html' %}
{% load static %}
{% block title %}ユーザートレース{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="trace_header">
    <h1>ユーザートレース</h1>
    <hr>
</div>
<div class="trace_main">
    <p>トレースしたいユーザーを選ぶどん！</p>
    <form action="{% url 'app:trace' %}" method="POST">
        <select class="select_line" name="user_trace">
            {% for other_user in other_users %}
            {% if other_user.id != user_id %}
            <option value="{{ other_user }}" selected>{{ other_user.name }}</option>
            {% endif %}
            {% endfor %}
        </select>
        <input type="submit" value="トレーースゥ！！">
        {% csrf_token %}
    </form>
</div>
<div class="back_to_table">
    <a href="{% url 'app:index' %}">戻る</a>
</div>
{% endblock %}

templates/index/upload.html
{% extends 'index.html' %}
{% load static %}
{% block title %}アップロード{% endblock %}

{% block head_extend %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="bg_blue">
<h1 class="name_title">{{class_name}}</h1>
<hr>
</div>
<form enctype="multipart/form-data" action="{% url 'app:upload' %}?class_name={{class_name}}" method="post">
    {% csrf_token %}
    <div class="mg30 form_title">
        タイトル : {{form.title}}
    </div>
    <div class="mg30 form_comment">
        コメント : {{form.comment}}
    </div>
    <div class="mg30 form_picture">
        画像 : 
        <label for="id_pictures" id="pictures_label">
            <text>ファイルを選択してください(切実)</text>
            {{form.pictures}}
        </label>
    </div>
    <div id="file-preview">
    </div>
    <div class="mg30 form_upload">
        <input type="submit" value="Upload" class="upload_button_1">
    </div>
</form>
<div class="back">
    <a href="{% url 'app:information' %}" value="戻る" class="back_button_1">戻る</a>
</div>
<script>
document.getElementById('id_pictures').onchange = function(){
    // 1枚だけ表示する
    console.log("テスト1");
    var len = document.getElementById('id_pictures').files.length;
    for (var i=0; i<len; i++){
        var file = document.getElementById('id_pictures').files[i];
        // ファイルのブラウザ上でのURLを取得する
        var blobUrl = window.URL.createObjectURL(file);
        // img要素に表示
        var img = new Image();
        img.src = blobUrl;
        img.style.width = "30%";
        document.getElementById('file-preview').append(img);
    }
};
</script>
{% endblock %}